# Generated by Django 4.2 on 2023-06-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='negative',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='neutral',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='positve',
            field=models.FloatField(default=0),
        ),
    ]
