# Generated by Django 4.2 on 2023-06-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_negative_post_neutral_post_positve'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='compound',
            field=models.FloatField(default=0),
        ),
    ]
